[package]
name = "viewer"
description = "Star-Navigator 3D viewer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "star-navigator"
path = "src/main.rs"

[dependencies]
bevy.workspace = true
catalog.workspace = true
flate2 = "1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["CssStyleDeclaration", "Document", "Element", "History", "HtmlElement", "Location", "Window"] }
